[package]
name = "treebitmap"
version = "0.1.0"
authors = ["Hroi Sigurdsson <hroi@asdf.dk>"]
description = "Fast IPv4/IPv6 lookup table/tree."
license = "MIT"
repository = "https://github.com/hroi/treebitmap"
documentation = "https://hroi.github.com/treebitmap/"
readme = "README.md"
keywords = ["ip", "routing", "trie", "lookup", "longest-match"]
exclude = ["test/*"]

[dependencies]
clippy = {version = "*", optional = true}

[dev-dependencies]
rand = "0.3.*"
lazy_static = "0.1.*"

[features]
full-bgp-tests = []
