[package]
name = "treebitmap"
version = "0.2.0"
authors = ["Hroi Sigurdsson <hroi@asdf.dk>"]
description = "Fast IPv4/IPv6 lookup trie."
license = "MIT"
repository = "https://github.com/hroi/treebitmap"
documentation = "https://hroi.github.com/treebitmap/"
readme = "README.md"
keywords = ["ip", "networking", "trie", "cidr"]
exclude = ["test/*"]

[dependencies]
clippy = {version = "0.0.41", optional = true}

[dev-dependencies]
rand = "0.3.*"
lazy_static = "0.1.*"

[features]
full-bgp-tests = []
dev = ["clippy"]
